# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-20 03:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160918_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='language',
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='snippet',
            field=models.CharField(default='string', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(default='default.title', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 3, 16, 7, 1947, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 3, 16, 7, 3385, tzinfo=utc)),
        ),
    ]
