# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-20 03:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170620_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 3, 20, 29, 120409, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 3, 20, 29, 120776, tzinfo=utc)),
        ),
    ]
