# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-20 03:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170620_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 3, 24, 34, 230618, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 3, 24, 34, 231218, tzinfo=utc)),
        ),
    ]
